name: feature_auth
description: Handles user authentication and sign-in logic.
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.1
  google_sign_in: ^6.3.0
  googleapis: 15.0.0
  googleapis_auth: ^1.6.0
  http: ^1.5.0
  url_launcher: ^6.3.2
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.1.0

  # Local Dependencies
  core_data:
    path: ../../core/core_data
  core_l10n:
    path: ../../core/core_l10n

dev_dependencies:
  flutter_test:
    sdk: flutter